### ISSUE TITLE
click empty space to select

### ISSUE THREAD

**Issue by alekksander** [mlm-games/CLauncher#15]
On list app clicking app line – but in empty space – selects it. The same doesn't apply in home screen. Please considered changing it for consistency. Thanks!

**Comment by mlm-games** [comment]
It seems to be working fine for me, can u send a video if possible?

**Comment by alekksander** [comment]
sure:
https://streamable.com/qofl0t

**Comment by mlm-games** [comment]
Thank you for the vid, It should now work like drawer apps from v5.1.2.
