### ISSUE TITLE
calendar shortcut

### ISSUE THREAD

**Issue by alekksander** [mlm-games/CLauncher#17]
seems this fork is really about minimalism further than some other forks, but please consider having calendar open upon clicking date under clock.

![Screenshot_20241213-065613_Clauncher](https://github.com/user-attachments/assets/f569278a-1d2e-409e-a1f9-8ec90064e650)

**Comment by mlm-games** [comment]
It does open the calendar for me on clicking date and the clock on clicking clock

**Comment by alekksander** [comment]
okay, just found out it has to be configured first by long pressing it just like any position in home view. thanks for reply, closing.
