### ISSUE TITLE
Suggestions for work profile.

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [mlm-games/CLauncher#18]
If possible can you change the gesture left to allow changing to work profile?

Currently all apps across profile are into one.
It also does not have the . Like in the Olauncher.Which makes it very confusing because it will show
_____________
contacts
contacts
clauncher
.........
____________

My suggestion is to either add a dot(.)
or allow left swipe/gesture to work profile which is kinda like keeping the old way.

Is it possible to implement any of that that?

Anyway huge thanks for your work Loved it from the bottom of my heart.

**Comment by mlm-games** [comment]
Thank you for ur kind words, 

As for work profile apps, Will try to add a dot(.) for work profile apps in the next version

**Comment by mlm-games** [comment]
Added (clone) suffix in v5.1.3, Again thank you for the appreciation...
